services:
  cassandra:
    image: cassandra:latest
    container_name: my-cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "DESC KEYSPACES"]
      interval: 15s
      timeout: 5s
      retries: 5

  cassandra-init:
    image: cassandra:latest
    container_name: cassandra-init
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./docker/cql:/scripts
    entrypoint: >
      sh -c "
        echo '==> Ждём запуска Cassandra…';
        until cqlsh cassandra -f /scripts/schema.cql; do
          echo '…ещё не готово, ждём 5 с…';
          sleep 5;
        done;
        echo '==> Схема загружена';
      "
    # После успешной инициализации можно сразу остановить контейнер
    restart: "no"

# Сеть создаётся автоматически

