name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Диагностика — покажем, что пришло на раннер
      - name: Show repo root
        run: |
          pwd
          ls -la
          echo "---- file gradlew ----"
          file gradlew || true
          echo "---- first line (visible CR if any) ----"
          head -n 1 gradlew | cat -A || true

      # На всякий случай лечим CRLF прямо на раннере
      - name: Normalize line endings for gradlew (LF)
        run: sed -i 's/\r$//' gradlew

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Ставим стабильную Java 21 для совместимости с Gradle
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # Маленькая проверка — печатаем версии
      - name: Gradle and Java versions
        run: |
          ./gradlew --version
          java -version

      - name: Build & Test with coverage
        run: ./gradlew clean test jacocoTestReport --no-daemon

      - name: Upload HTML coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-html
          path: build/reports/jacoco/test/html

      - name: Jacoco PR Comment
        if: ${{ github.event_name == 'pull_request' }}
        uses: madrapps/jacoco-report@v1.7.1
        with:
          paths: build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ github.token }}
          title: 'Coverage Report'
          min-coverage-overall: 0
          min-coverage-changed-files: 0
