name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # выдаем права на gradlew, делаем его исполняемым нужно для linux раннера github actions
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build & Test with coverage
        run: ./gradlew clean test jacocoTestReport --no-daemon

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build & Test with coverage
        run: ./gradlew clean test jacocoTestReport --no-daemon

      - name: Upload HTML coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-html
          path: build/reports/jacoco/test/html

      # Комментарий в PR с кратким отчётом покрытия (без сторонних сервисов)
      - name: Jacoco PR Comment
        if: ${{ github.event_name == 'pull_request' }}
        uses: madrapps/jacoco-report@v1.7.1
        with:
          paths: build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ github.token }}
          title: 'Coverage Report'
          min-coverage-overall: 0
          min-coverage-changed-files: 0
